### ISSUE TITLE
AttributeError: module 'hok' has no attribute 'hok1v1'

### ISSUE THREAD

**Issue by 1329844541** [tencent-ailab/hok_env#67]
susan@MOU-QING-PING:~/hok_env/hok_env/hok/hok1v1/unit_test$ python3 test_env.py
Traceback (most recent call last):
  File "test_env.py", line 5, in <module>
    from hok.hok1v1 import HoK1v1
  File "/home/susan/hok_env/hok_env/hok/hok1v1/__init__.py", line 11, in <module>
    from hok.hok1v1.env1v1 import HoK1v1
  File "/home/susan/hok_env/hok_env/hok/hok1v1/env1v1.py", line 18, in <module>
    import hok.hok1v1.lib.interface as interface
AttributeError: module 'hok' has no attribute 'hok1v1'

![120aaf77544b68c62118b64fed0c4c3](https://github.com/user-attachments/assets/a5db0426-dc51-449e-8316-f7e59ff16fb2)

**Comment by JackyXiangcheng** [comment]
Hello, Susan. You can find the directories including hok1v1 and just try to follow all instructions in order and carefully, also check the absolute path and relative path. Hope this helps you.

**Comment by yehaim** [comment]
Same problem with environment:
```
WSL2: Ubuntu 20.04.6 LTS
Python: 3.6.13
hok package: installed by pip install -e .
bashrc: 
export PATH=/home/yehai/hok_env/hok_env/hok:$PATH
export PYTHONPATH=/home/yehai/hok_env/hok_env/hok:$PYTHONPATH
```

![image](https://github.com/user-attachments/assets/410505d3-6d4f-4679-92bd-77a97e1eb24f)

Solved it by modify code in `hok_env/hok_env/hok/hok1v1/env1v1.py`
```
# import hok.hok1v1.lib.interface as interface
# replace with
from hok.hok1v1.lib import interface as interface
```
