### ISSUE TITLE
connectionError

### ISSUE THREAD

**Issue by Nemocccc** [tencent-ailab/hok_env#72]
when i got to the step 
```bash
python test_env.py
```
received Error:
```bash
127.0.0.1:23432 127.0.0.1
======= test_send_action
camp_config {'mode': '1v1', 'heroes': [[{'hero_id': 189}], [{'hero_id': 112}]]}
common_ai [False, True]
try to get first state...
Traceback (most recent call last):
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/http/client.py", line 1287, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/http/client.py", line 1333, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/http/client.py", line 1282, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f2c1b9fb438>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=23432): Max retries exceeded with url: /v2/newGame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c1b9fb438>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_env.py", line 111, in <module>
    test_send_action(env, common_ai=[False, True], eval=False, camp_config=camp_config)
  File "test_env.py", line 48, in test_send_action
    camp_config, use_common_ai=common_ai, eval=eval
  File "/home/nemo/workspace/hok_env/hok_env/hok/hok1v1/env1v1.py", line 642, in reset
    eval_mode=self.eval_mode,
  File "/home/nemo/workspace/hok_env/hok_env/hok/common/gamecore_client.py", line 109, in start_game
    self._send_http_request("newGame", data)
  File "/home/nemo/workspace/hok_env/hok_env/hok/common/gamecore_client.py", line 142, in _send_http_request
    resp = requests.post(url=url, json=data, headers=headers, verify=False)
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/nemo/miniconda3/envs/hok_env/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=23432): Max retries exceeded with url: /v2/newGame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c1b9fb438>: Failed to establish a new connection: [Errno 111] Connection refused',))
(hok_env)
```
any ideas?

**Comment by taiyimen** [comment]
> The `127.0.0.1` in wsl is not same with `127.0.0.1` in the windows. You need to use the nameserver of the wsl to access the server process running on windows.
> 
> ![image](https://user-images.githubusercontent.com/17291060/208573024-333d86a7-d09b-42d8-8d0d-e03350dde1d7.png)
> 
> See also https://learn.microsoft.com/en-us/windows/wsl/networking
